"""quant_guard.backtest.report: 增强回测报告生成。

读取 Freqtrade 回测结果文件（zip 内 JSON），追加资金费、手续费、强平风险、
回撤分析，输出 Markdown 报告到 docs/BACKTEST_VALIDATION.md。
"""

import json
import zipfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass
class BacktestMetrics:
    """回测核心指标。"""

    strategy: str
    timerange: str
    total_trades: int
    total_profit_pct: float
    max_drawdown_pct: float
    win_rate: float
    avg_duration: str = ""
    sharpe: float = 0.0
    sortino: float = 0.0
    total_fee: float = 0.0  # 手续费估算
    total_funding_fee: float = 0.0  # 资金费估算
    has_funding_data: bool = False
    has_mark_price: bool = False


@dataclass
class BacktestReportData:
    """回测报告数据。"""

    metrics: BacktestMetrics
    liquidation_warnings: List[str] = field(default_factory=list)
    phase1_passed: bool = False
    phase2_passed: bool = False
    notes: List[str] = field(default_factory=list)


def load_backtest_result(result_path: str) -> dict:
    """从 Freqtrade 回测结果文件（zip 或 json）加载原始数据。

    参数：
        result_path: zip 文件路径或 json 文件路径

    返回：
        回测结果字典
    """
    path = Path(result_path)
    if not path.exists():
        raise FileNotFoundError(f"backtest result not found: {result_path}")

    if path.suffix == ".zip":
        with zipfile.ZipFile(path) as zf:
            json_names = [n for n in zf.namelist() if n.endswith(".json")]
            if not json_names:
                raise ValueError(f"no json in zip: {result_path}")
            with zf.open(json_names[0]) as f:
                return json.loads(f.read().decode("utf-8"))
    else:
        with open(path, encoding="utf-8") as f:
            return json.load(f)


def _profit_total_pct(s: dict) -> float:
    """Freqtrade profit_total 为小数比例，需乘 100 得到百分比。"""
    if s.get("profit_total_pct") is not None:
        return float(s["profit_total_pct"])
    return float(s.get("profit_total", 0)) * 100


def _max_drawdown_pct(s: dict) -> float:
    """Freqtrade max_drawdown_abs 为 USDT 绝对值，百分比应读 max_drawdown_account。"""
    ratio = s.get("max_drawdown_account", s.get("max_relative_drawdown", 0))
    return float(ratio) * 100


def extract_metrics(raw: dict) -> BacktestMetrics:
    """从原始回测结果提取核心指标。"""
    strategy_dict = raw.get("strategy", {})
    if not strategy_dict:
        raise ValueError("no strategy data in backtest result")

    strategy_name = list(strategy_dict.keys())[0]
    s = strategy_dict[strategy_name]

    total_trades = s.get("total_trades", 0)
    wins = s.get("wins", 0)
    win_rate = (wins / total_trades * 100) if total_trades > 0 else 0

    return BacktestMetrics(
        strategy=strategy_name,
        timerange=f"{s.get('backtest_start', 'N/A')} ~ {s.get('backtest_end', 'N/A')}",
        total_trades=total_trades,
        total_profit_pct=_profit_total_pct(s),
        max_drawdown_pct=_max_drawdown_pct(s),
        win_rate=round(win_rate, 2),
        avg_duration=str(s.get("holding_avg", "")),
        sharpe=s.get("sharpe", 0),
        sortino=s.get("sortino", 0),
        total_fee=s.get("fee_total", 0),
        total_funding_fee=s.get("funding_total", 0),
        has_funding_data="funding_total" in s,
        has_mark_price=s.get("has_mark_price", False),
    )


def generate_report(data: BacktestReportData) -> str:
    """生成 Markdown 格式的增强回测报告。

    参数：
        data: BacktestReportData

    返回：
        Markdown 字符串
    """
    m = data.metrics
    lines: List[str] = []

    lines.append("# Backtest Validation Report")
    lines.append("")
    lines.append(f"**策略**: {m.strategy}")
    lines.append(f"**时间范围**: {m.timerange}")
    lines.append(f"**生成时间**: auto-generated by quant_guard.backtest.report")
    lines.append("")
    lines.append("---")
    lines.append("")

    # 核心指标
    lines.append("## 核心指标")
    lines.append("")
    lines.append(f"| 指标 | 值 |")
    lines.append(f"|---|---|")
    lines.append(f"| 总交易数 | {m.total_trades} |")
    lines.append(f"| 总收益率 | {m.total_profit_pct:.2f}% |")
    lines.append(f"| 最大回撤 | {m.max_drawdown_pct:.2f}% |")
    lines.append(f"| 胜率 | {m.win_rate:.1f}% |")
    lines.append(f"| 平均持仓时长 | {m.avg_duration} |")
    lines.append(f"| Sharpe | {m.sharpe:.2f} |")
    lines.append(f"| Sortino | {m.sortino:.2f} |")
    lines.append("")

    # 成本分析
    lines.append("## 成本分析")
    lines.append("")
    lines.append(f"| 成本项 | 金额 (USDT) | 说明 |")
    lines.append(f"|---|---|---|")
    lines.append(f"| 手续费 | {m.total_fee:.4f} | 交易所交易手续费 |")

    if m.has_funding_data:
        lines.append(f"| 资金费 | {m.total_funding_fee:.4f} | 每 8h 结算 |")
    else:
        lines.append(
            f"| 资金费 | ⚠️ 缺失 | 回测未包含资金费数据，收益可能虚高 |"
        )

    total_cost = m.total_fee + m.total_funding_fee
    lines.append(f"| **总成本** | **{total_cost:.4f}** | |")
    lines.append("")

    # 强平风险
    lines.append("## 强平风险分析")
    lines.append("")
    if data.liquidation_warnings:
        for w in data.liquidation_warnings:
            lines.append(f"- ⚠️ {w}")
    else:
        lines.append("- 无强平风险警告")
    lines.append("")

    if not m.has_mark_price:
        lines.append(
            "> ⚠️ **风险提示**: 回测未使用标记价格，强平风险分析可能不准确。"
            "正式部署前需确保使用标记价格数据。"
        )
        lines.append("")

    # 阶段门禁结论
    lines.append("## 阶段门禁结论")
    lines.append("")
    lines.append(f"- **Ph1 通过**: {'✅ 是' if data.phase1_passed else '❌ 否'}")
    lines.append(f"- **Ph2 通过**: {'✅ 是' if data.phase2_passed else '❌ 否'}")
    lines.append("")

    if data.notes:
        lines.append("## 备注")
        lines.append("")
        for note in data.notes:
            lines.append(f"- {note}")
        lines.append("")

    # 结论
    lines.append("## 结论")
    lines.append("")
    if data.phase1_passed and data.phase2_passed:
        lines.append("✅ **允许进入 dry-run 阶段**。")
        lines.append("")
        lines.append("下一步：")
        lines.append("1. 在 dry-run 环境运行 1-2 周")
        lines.append("2. 对比 dry-run 与回测结果差异")
        lines.append("3. 完成 docs/DRYRUN_VALIDATION.md")
        lines.append("4. 通过 docs/LIVE_SAFETY_CHECKLIST 后进入小资金实盘")
    else:
        lines.append("❌ **不允许进入 dry-run 阶段**。")
        lines.append("")
        if not data.phase1_passed:
            lines.append("- Ph1 未通过：策略需改进或参数需优化")
        if not data.phase2_passed:
            lines.append("- Ph2 未通过：回测需包含资金费/强平风险分析")
    lines.append("")
    lines.append("---")
    lines.append("")

    return "\n".join(lines)


def generate_and_save(
    result_path: str,
    output_path: str = "docs/BACKTEST_VALIDATION.md",
) -> str:
    """加载回测结果，生成增强报告并保存到文件。

    参数：
        result_path: Freqtrade 回测结果文件路径（zip 或 json）
        output_path: 输出 Markdown 文件路径

    返回：
        生成的 Markdown 报告字符串
    """
    raw = load_backtest_result(result_path)
    metrics = extract_metrics(raw)

    # 判断阶段门禁
    liquidation_warnings: List[str] = []
    notes: List[str] = []

    # Ph1 门禁：有交易、无前视（简化判断）
    phase1_passed = metrics.total_trades > 0

    # Ph2 门禁：含资金费数据
    phase2_passed = metrics.has_funding_data
    if not metrics.has_funding_data:
        notes.append("回测缺少资金费数据，Ph2 未通过")
    if not metrics.has_mark_price:
        notes.append("回测缺少标记价格数据，强平分析不完整")

    # 强平风险警告
    if metrics.max_drawdown_pct > 50:
        liquidation_warnings.append(
            f"最大回撤 {metrics.max_drawdown_pct:.1f}% 过高，存在强平风险"
        )

    data = BacktestReportData(
        metrics=metrics,
        liquidation_warnings=liquidation_warnings,
        phase1_passed=phase1_passed,
        phase2_passed=phase2_passed,
        notes=notes,
    )

    report = generate_report(data)

    # 保存到文件
    out = Path(output_path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(report, encoding="utf-8")

    return report
